### ISSUE TITLE
adding filter capability

### ISSUE THREAD

**Issue by imvisiontech** [intelsdi-x/snap-plugin-collector-psutil#20]
for example: 
instead of writing the same requirements for cpu0,cpu1,cpu2 etc... simply write:
    "/intel/psutil/_/guest": {},
    "/intel/psutil/_/guest_nice": {},
    "/intel/psutil/_/idle": {},
    "/intel/psutil/_/iowait": {},
    "/intel/psutil/_/irq": {},
    "/intel/psutil/_/nice": {},
    "/intel/psutil/_/softirq": {},
    "/intel/psutil/_/steal": {},
    "/intel/psutil/_/stolen": {},
    "/intel/psutil/_/system": {},
    "/intel/psutil/*/user": {},

**Comment by IRCody** [comment]
@imvisiontech: Sorry for the delay in responding. 

I'm not sure I understand the request. Write this where?

**Comment by jcooklin** [comment]
The psutil plugin exposes these cpu metrics as dynamic metrics meaning that you can provide in the manifest a value for the specific core you want metrics for or get them all.

Portion of the task manifest:
```
snapctl metric list
NAMESPACE 				 VERSIONS
/intel/psutil/cpu/*/guest 		 8
/intel/psutil/cpu/*/guest_nice 		 8
/intel/psutil/cpu/*/idle 		 8
/intel/psutil/cpu/*/iowait 		 8
/intel/psutil/cpu/*/irq 		 8
/intel/psutil/cpu/*/nice 		 8
/intel/psutil/cpu/*/softirq 		 8
/intel/psutil/cpu/*/steal 		 8
/intel/psutil/cpu/*/stolen 		 8
/intel/psutil/cpu/*/system 		 8
/intel/psutil/cpu/*/user 		 8
/intel/psutil/cpu/cpu-total/guest 	 8
....
```

A task manifest like the following:
```
---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      metrics:
        /intel/psutil/cpu/*/user: {}
```

Results in the following collection:
![](https://www.evernote.com/l/AA2Dd4pUyf9IgZVNS4rgt0KSTuU-eeTiRfYB/image.png)

If you want to collect metrics for a single core your task manifest would look like:
```
---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      metrics:
        /intel/psutil/cpu/cpu0/user: {}
```
